### ISSUE TITLE
GDPR Compliance

### ISSUE THREAD

**Issue by Stanzilla** [phpbb-extensions/googleanalytics#71]
Any plans to change this extension to, at least, set `ga('set', 'anonymizeIp', true);` by default or add options for it to the UI. I know you can write extensions for this extension but the default should probably changed for the base extension as well in compliance with GDPR.

**Comment by VSEphpbb** [comment]
There's currently an add-on for this.
https://www.phpbb.com/customise/db/extension/googleanalytics/support/topic/145856?p=436991#p436991

**Comment by VSEphpbb** [comment]
Closed by #72
