### ISSUE TITLE
OptOut

### ISSUE THREAD

**Issue by bombcheck** [phpbb-extensions/googleanalytics#73]
Any plans to add code so that users can opt-out of google analytics?

**Comment by VSEphpbb** [comment]
Nope. Opt Out is not required so long as we have an option to anonymize user IPs, which will come in the next release of this ext.

It also won't be added to this extension for the very reason that phpBB itself, and other extensions for it could very well have a need for an opt-out. To add that at the extension level would mean that a forum could end up with multiple opt out dialogs, which would be very annoying to users. 

So it is my opinion that if phpBB does not have an opt out built in to it at the core level, then opt out should be it's own separate extension that users can install.

**Comment by bombcheck** [comment]
Well thats ok :)

Just modified the extension in my board and added the following script to `overall_header_stylesheets_after.html` just after `{% if GOOGLEANALYTICS_ID %}`:

`<script type="text/javascript">
	var gaProperty = '{{ GOOGLEANALYTICS_ID }}';
	var disableStr = 'ga-disable-' + gaProperty;
	if (document.cookie.indexOf(disableStr + '=true') > -1) {
	window[disableStr] = true;
	}
	function gaOptout() {
	document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
	window[disableStr] = true;
	}
</script>
`
