### ISSUE TITLE
Issue with googleanalytics_id

### ISSUE THREAD

**Issue by Galixte** [phpbb-extensions/googleanalytics#74]
Hi @VSEphpbb,

did you see this: https://www.phpbb.com/customise/db/extension/phpbb_gallery/support/topic/179741?p=627346#p627346 ?

What do you think?

**Comment by DavidIQ** [comment]
The author, who said would send a pr, never sent one so there's no reason why any of us would have seen that post.

**Comment by Galixte** [comment]
Ok but is it needed or not? I can submit a new PR.

**Comment by VSEphpbb** [comment]
It's not needed. There is no way that google analytics function affects the permission settings of other extensions.

**Comment by VSEphpbb** [comment]
Fixed by #79
