### ISSUE TITLE
Opt-in

### ISSUE THREAD

**Issue by R3gi** [phpbb-extensions/googleanalytics#91]
Hi,
due the changing legislative taking effect from Jan 2022 we'll not be allowed to use cookies for analytical purposes **without user's opt-in consent**. If I get this right, it means we cannot store cookies until the user clicks the "track me" button.

Are there any plans to reflect this change? If not, are there any alternative solutions?

Article: [Stricter Rules for Cookies in the Czech Republic from 2022](https://ceelegalmatters.com/czech-republic/17964-stricter-rules-for-cookies-in-the-czech-republic-from-2022)

**Comment by iMattPro** [comment]
phpBB already has an opt-in to accept cookie tracking feature built in to it. Anything related to this will be a phpBB issue, and not this extension's.
